### ISSUE TITLE
バリデーションエラーの「translation missing」を解消する

### ISSUE THREAD

**Issue by arinko-ya** [Kazuya-Sakashita/zerowan-app#10]
## 概要
バリデーションエラーが translation missing となっておりエラー内容が表示されていないので表示されるように修正する。

## 完了条件
- 新規登録画面においてバリデーションエラーが適切に表示されていること

## 参考
https://qiita.com/ken_sasaki2/items/0c566ced53f7ee47d67d

## 参考デザイン
https://www.figma.com/file/GXxYjeIB2Ra2VY1l3psYZb/zerowan_app?node-id=10%3A713

**Comment by Kazuya-Sakashita** [comment]
アカウント情報の更新の際にパスワード入力されていない場合は、下記の表示になるように修正しました。

<img width="1044" alt="スクリーンショット 2022-07-20 20 05 15" src="https://user-images.githubusercontent.com/64903209/179968063-35389ce1-736f-4f59-ba9f-e8f10e2dcff6.png">

**Comment by arinko-ya** [comment]
すみません対象画面書いてませんでしたね。。
新規登録画面の方の対応をお願いします！

**Comment by Kazuya-Sakashita** [comment]
こういうことでしょうか？
この理解であってますでしょうか？


<img width="979" alt="スクリーンショット 2022-07-20 20 53 58" src="https://user-images.githubusercontent.com/64903209/179975893-e6838cf9-6330-4df3-a626-329dca30dce5.png">

**Comment by arinko-ya** [comment]
あってますー！

**Comment by Kazuya-Sakashita** [comment]
よかったです。

**Comment by Kazuya-Sakashita** [comment]
修正したものをgit pushしています。
