### ISSUE TITLE
ペットのお気に入り機能を追加する

### ISSUE THREAD

**Issue by arinko-ya** [Kazuya-Sakashita/zerowan-app#43]
## 概要
ペットのお気に入り機能を追加する

## 完了条件
- トップページ、マイページなどのペット一覧にお気に入りに登録するためのボタンが設置されていること
- 自身の登録したペットの場合はボタンを押下できない（disable になっている）こと
- ペット詳細ページにお気に入りに登録するためのボタンが設置されていること
- 関連するテストが追加され、全てパスしていること

## 参考デザイン
※２パターン用意しているので実装しやすい方で大丈夫です。

### ペット一覧
https://www.figma.com/file/GXxYjeIB2Ra2VY1l3psYZb/zerowan_app?node-id=10%3A1677
https://www.figma.com/file/GXxYjeIB2Ra2VY1l3psYZb/zerowan_app?node-id=10%3A1705

### ペット詳細
https://www.figma.com/file/GXxYjeIB2Ra2VY1l3psYZb/zerowan_app?node-id=307%3A3
https://www.figma.com/file/GXxYjeIB2Ra2VY1l3psYZb/zerowan_app?node-id=353%3A189

## 補足
- 実現可能な範囲までで OK です。

**Comment by Kazuya-Sakashita** [comment]
- 自身の登録したペットの場合はボタンを押下できない（disable になっている）こと

ということでしたが、理解不足で本人の場合は、ボタンが表示されないようにしてました。
button_toのオプションでdisabled設定する方に変更した方が良いでしょうか。
アプリの場合、一般的でしょうか？
