### ISSUE TITLE
マイページに未読メッセージ通知を出すための設計を考える

### ISSUE THREAD

**Issue by arinko-ya** [Kazuya-Sakashita/zerowan-app#64]
## 概要
マイページに未読メッセージ通知を出すための設計を考える
本タスクでは設計のみのため実装は別タスクで行うこととする
テキストベースまたはポンチ絵を使っても良い

## 完了条件
- 本チケットのコメント欄に設計案が記載されていること

## 参考デザイン
https://www.figma.com/file/GXxYjeIB2Ra2VY1l3psYZb/zerowan_app?type=design&node-id=17-610&mode=design&t=DspBoM3h9gGU3d5K-4

**Comment by Kazuya-Sakashita** [comment]
下記でどうでしょうか。
1. messages テーブルに read_atを追加
2. メッセージが読み込まれたら日時を書き込む
 （読み込まれた判定としては、相手がルームに入ったときとする）
3. read_atカラムに日時がなければ未読、日時が記録されていれば読まれたと判定

**Comment by arinko-ya** [comment]
すみません見逃していました；

ありがとうございます！
記載いただいた内容で問題なさそうです。

Tips ですが、この手の通知機能は NoSQL やキャッシュサーバーを利用して実装すると DB への書き込みアクセスを削減したり、データ量を節約したりが可能になったりします（今回はどちらも用意していないので RDB オンリーですが）
