### ISSUE TITLE
会員登録のテストを作成する

### ISSUE THREAD

**Issue by arinko-ya** [Kazuya-Sakashita/zerowan-app#9]
## 概要
会員登録のテストを作成する。
テストケースは以下の通り。
- models
  - user
    - email
      - 値がない場合にバリデーションエラーが発生すること
      - 重複して登録しようとした場合にバリデーションエラーが発生すること
    - password
      - 6文字に満たない場合にバリデーションエラーが発生すること
  - profile
    - name
      - 値がない場合にバリデーションエラーが発生すること
    - address
      - 値がない場合にバリデーションエラーが発生すること
    - phone_number
      - 値がない場合にバリデーションエラーが発生すること
      - 文字列が入っていた場合にバリデーションエラーが発生すること
    - birthday
      - 値がない場合にバリデーションエラーが発生すること
    - breeding_experience
      - 値がない場合にバリデーションエラーが発生すること
- controllers
  - new
    - 登録画面が描画されること
  - confirm
    - 各パラメーターに正しく値が設定された場合、確認画面が描画されること
    - 各パラメーターに値が正しく設定されなかった場合、登録画面が描画されること
  - create
    - 各パラメーターに正しく値が設定された場合、home 画面が描画されること
    - 各パラメーターに正しく値が設定された場合、ユーザーが正しく作成されること
    - 各パラメーターに値が正しく設定されなかった場合、登録画面が描画されること
    - flash メッセージが正しく表示されていること
      - `expect(flash[:notice]).to eq '本人確認用のメールを送信しました。メール内のリンクからアカウントを有効化させてください。'` みたいな感じで確認可能です
    - params に back: true が設定されている場合、登録画面が描画されること
  - confirmation
    - params にユーザーの confirmation_token が正しく含まれていた場合、ログイン画面が描画されること
    - flash メッセージが正しく表示されていること
    - ユーザーが確認済み状態になっていること
    - params にユーザーの confirmation_token が含まれていない場合、エラー画面が描画されること
      - 中身は整ってないままでも OK です
- features
  - 登録画面
    - 登録画面へのアクセスで正常に画面が描画されること
    - 表示される内容が正しいこと（フォームの内容やボタン、リンク等が正しく表示されていること）
    - 正しく値を入力した場合、登録確認画面に遷移すること
    - 値が全て入力されていなかった場合、バリデーションエラーの内容が表示されること
  - 確認画面
    - 表示される内容が正しいこと
    - 「登録」ボタンを押下で Home 画面に遷移すること
    - flash メッセージが正しく表示されていること
    - 「登録」ボタンを押下でメール送信処理が行われること
    - 「修正する」ボタンを押下で登録画面に戻れること
  - 本人確認
    - メールに含まれる確認トークンで本人確認 URL にアクセスするとログイン画面に遷移すること
    - flash メッセージが正しく表示されていること

※ その他必要そうなものがあったら足していただいて OK です。

## 備考
- テストケースに合わせるためや、テストをしやすいように実装を改変するのはありです。
- テストが通らなかった際に**テストコード**を実装に寄せてしまう、というのは結構ありがちなのですが良くないパターンですのでご注意ください。

**Comment by Kazuya-Sakashita** [comment]
下記の部分ですが、更新時が空でも登録（更新）できるという意味でしょうか？
 　　　 models・password・更新時は空でも登録ができること

プロフィール情報については、パスワードなしで変更できるようにしています。
Userアカウント情報はパスワードありでなければ更新できません。

**Comment by arinko-ya** [comment]
oh...そうでした；
消しておきます！

**Comment by arinko-ya** [comment]
すみません、features のテストを失念していたので追加しています。。
features のテストは画面操作のテストで、主に capybara を使用します。
参考: https://qiita.com/koki_73/items/c033e7a059192ec73c25

もし詰まったらご相談ください！
